/** Bundled fallback tips — merged with server `loader_tips` / remote JSON when available. */
export const DEFAULT_LOADER_TIPS: readonly string[] = [
  "A consistent pre-shot routine can lower scores more than buying new clubs.",
  "In tennis, footwork wins points: get to the ball early and set your base before you swing.",
  "Short game practice often drops more strokes than another hour on the driving range.",
  "Hydrate before you feel thirsty — even mild dehydration hurts focus and reaction time.",
  "Film one swing from face-on and one from down-the-line; small fixes are easier to see on video.",
  "Basketball players who track teammates' eyes pass cleaner under pressure.",
  "Soccer: scanning the field before you receive the ball buys you an extra second every touch.",
  "Golfers who pick a small target commit better than those who aim at the whole fairway.",
  "Rest days are training days — muscles adapt when you recover, not only when you grind.",
  "Pickleball rewards patience at the kitchen line; wait for a ball you can attack.",
  "Swimmers shave time by tightening streamline off every wall, not just the first lap.",
  "Baseball hitters who breathe out through contact stay looser and drive the ball farther.",
  "Cycling: steady cadence on climbs beats mashing gears and burning out early.",
  "Volleyball teams that call the ball early have fewer collisions and faster transitions.",
  "Runners improve economy with strides and drills, not only by adding weekly mileage.",
  "Yoga and mobility work help athletes in every sport move safer and recover faster.",
  "Football linebackers who read the quarterback's eyes react a step quicker to play-action.",
  "Cricket batsmen who watch the seam out of the hand pick length earlier.",
  "Hockey players who keep sticks on the ice intercept more passes in the neutral zone.",
  "Skateboarders land cleaner when they look at the landing spot, not at their feet.",
  "Wrestlers who control tie-ups control the match — hands inside first.",
  "Rowers sync with the stroke seat; rhythm beats raw power in an eight.",
  "Boxers win rounds with jab discipline before they hunt for the knockout.",
  "Surfers catch more waves by reading sets from outside, not paddling blind inside.",
  "Climbers rest on straight arms to save grip strength on longer routes.",
  "Skiers steer with ankles and shins, not by leaning back on steep runs.",
  "Lacrosse midfielders who move the ball in two passes beat one-on-one hero plays.",
  "Track sprinters drive knees forward; distance runners think quick, light turnover.",
  "A coach's best feedback is specific: one cue beats five fixes at once.",
  "Showing up prepared — warmed up and on time — is respect for your coach and teammates.",
] as const;
