/**
 * REST paths for the NetQwix API (source of truth for mobile + OpenAPI contract).
 * See `docs/API-CONTRACT.md` and `npm run sync:api-contract`.
 *
 * Mount prefixes match `nq-backend-main/routes.ts`:
 * `router.use("/user", userRoute)`, `/auth`, `/master`, `/trainer`, `/trainee`,
 * `/transaction`, `/common`, `/report`, `/admin`, `/notifications`.
 *
 * Source files (keep in sync when backend changes):
 * - `src/modules/auth/authRoutes.ts`
 * - `src/modules/user/userRoutes.ts`
 * - `src/modules/master/masterRoutes.ts`
 * - `src/modules/trainer/trainerRoutes.ts`
 * - `src/modules/trainee/traineeRoute.ts`
 * - `src/modules/transaction/transactionRoutes.ts`
 * - `src/modules/common/commonRoutes.ts`
 * - `src/modules/report/reportRoutes.ts`
 * - `src/modules/admin/adminRoutes.ts`
 * - `src/modules/notifications/notificationsRoutes.ts`
 */
export const API_ROUTES = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    sessionsRegister: "/auth/sessions/register",
    sessions: "/auth/sessions",
    sessionsRevoke: "/auth/sessions/revoke",
    sessionsRevokeOthers: "/auth/sessions/revoke-others",
    sessionsRevokeAll: "/auth/sessions/revoke-all",
    signup: "/auth/signup",
    signupCheckContact: "/auth/signup/check-contact",
    signupOtpSend: "/auth/signup/otp/send",
    signupOtpVerify: "/auth/signup/otp/verify",
    forgotPassword: "/auth/forgot-password",
    confirmResetPassword: "/auth/confirm-reset-password",
    verifyGoogleLogin: "/auth/verify-google-login",
    verifyAppleLogin: "/auth/verify-apple-login",
    magicLinkRequest: "/auth/magic-link/request",
    magicLinkVerify: "/auth/magic-link/verify",
    wakeUpStart: "/auth/wake-up/start",
    wakeUpConfirm: "/auth/wake-up/confirm",
  },
  user: {
    me: "/user/me",
    deleteMe: "/user/me",
    chatPublicKeyMe: "/user/me/chat-public-key",
    chatPublicKey: (userId: string) => `/user/${userId}/chat-public-key` as const,
    signUp: "/user/sign-up",
    scheduledMeetings: "/user/scheduled-meetings",
    updateBookedSession: (id: string) => `/user/update-booked-session/${id}` as const,
    shareClips: "/user/share-clips",
    inviteFriend: "/user/invite-friend",
    rating: "/user/rating",
    addTraineeClip: (id: string) => `/user/add-trainee-clip/${id}` as const,
    sendFriendRequest: "/user/send-friend-request",
    acceptFriendRequest: "/user/accept-friend-request",
    cancelFriendRequest: "/user/cancel-friend-request",
    rejectFriendRequest: "/user/reject-friend-request",
    friendRequests: "/user/friend-requests",
    sentFriendRequests: "/user/sent-friend-requests",
    friends: "/user/friends",
    removeFriend: "/user/remove-friend",
    blockUser: "/user/block-user",
    unblockUser: "/user/unblock-user",
    blockedUsers: "/user/blocked-users",
    reportUser: "/user/report-user",
    updateAccountPrivacy: "/user/update-account-privacy",
    /** Profile-visibility settings (last active, search visibility, message
     *  requests from non-friends). Persisted on the user document under
     *  `privacy_visibility`. */
    updateProfileVisibility: "/user/update-profile-visibility",
    /** GDPR / India DPDP data-export request. Backend enqueues a job and
     *  emails the user when the archive is ready. */
    requestDataExport: "/user/data-export/request",
    dataExportStatus: "/user/data-export/status",
    /** Trainer 2FA — enrol a trusted device, send/verify OTP, list/revoke. */
    twoFactorStatus: "/user/2fa/status",
    twoFactorEnable: "/user/2fa/enable",
    twoFactorDisable: "/user/2fa/disable",
    twoFactorChallenge: "/user/2fa/challenge",
    twoFactorVerify: "/user/2fa/verify",
    twoFactorTrustedDevices: "/user/2fa/trusted-devices",
    twoFactorRevokeTrustedDevice: (id: string) =>
      `/user/2fa/trusted-devices/${encodeURIComponent(id)}` as const,
    getAllTrainee: "/user/get-all-trainee",
    getAllUsers: "/user/get-all-users",
    getAllTrainer: "/user/get-all-trainer",
    updateTrainerCommission: "/user/update-trainer-commission",
    registerUserWithStripe: "/user/register-user-with-stripe",
    updateKycStatus: "/user/update-kyc-status",
    createVerificationSession: "/user/create-verification-session",
    bookingList: "/user/booking-list",
    bookingListById: "/user/booking-list-by-id",
    bookingById: (id: string) => `/user/booking/${id}` as const,
    sessionDetail: (id: string) => `/user/session-detail/${id}` as const,
    sessionJoinReadiness: (id: string) => `/user/session-join-readiness/${id}` as const,
    sessionHandoff: (id: string) => `/user/session-handoff/${id}` as const,
    sessionTimeline: (id: string) => `/user/session-timeline/${id}` as const,
    stripeAccountVerification: "/user/stripe-account-verification",
    checkStripeVerification: "/user/check-stripe-verification",
    updateRefundStatus: "/user/update-refund-status",
    writeUs: "/user/write-us",
    raiseConcern: "/user/raise-concern",
    getWriteUs: "/user/write-us",
    getRaiseConcern: "/user/raise-concern",
    updateContactUsStatus: "/user/update-contact-us-status",
    updateRaisedConcernTicket: "/user/update-raised-concern-ticket",
    myRaiseConcerns: "/user/my-raise-concerns",
    myReferrals: "/user/my-referrals",
    allOnlineUser: "/user/all-online-user",
    updateMobileNumber: "/user/update-mobile-number",
    updateNotificationsSettings: "/user/update-notifications-settings",
    updateTrainerStatus: "/user/update-trainer-status",
    onlineAvailability: "/user/online-availability",
    autoDeclineOutsideHours: "/user/auto-decline-outside-hours",
    deleteUser: (id: string) => `/user/delete-user/${id}` as const,
    approveExpert: (id: string) => `/user/approve-expert/${id}` as const,
    storage: "/user/storage",
    storageCheckout: "/user/storage/checkout",
    /** Phase 2 — current lifecycle state (deleted / hibernated / pending). */
    lifecycle: "/user/me/lifecycle",
    /** Phase 2 — OTP-gated deletion (step 1: password + reason → OTP sent). */
    deletionRequest: "/user/me/deletion/request",
    /** Phase 2 — OTP-gated deletion (step 2: OTP → freeze + 15d window). */
    deletionConfirm: "/user/me/deletion/confirm",
    /** Phase 2 — clear pending deletion. */
    deletionCancel: "/user/me/deletion/cancel",
    /** Phase 2 — start hibernation (sends OTP). */
    hibernateRequest: "/user/me/hibernate/request",
    /** Phase 2 — confirm hibernation (OTP → hibernated_at). */
    hibernateConfirm: "/user/me/hibernate/confirm",
  },
  referral: {
    program: "/referral/program",
    resolve: (code: string) => `/referral/resolve/${encodeURIComponent(code)}` as const,
    invite: "/referral/invite",
    invites: "/referral/invites",
    rewards: "/referral/rewards",
    benefits: "/referral/benefits",
    previewCheckout: "/referral/preview-checkout",
  },
  tips: {
    list: "/tips",
  },
  banners: {
    list: "/banners",
  },
  cms: {
    manifest: "/cms/manifest",
    faq: "/cms/faq",
    legal: (slug: string) => `/cms/legal/${slug}` as const,
    pages: "/cms/pages",
    page: (slug: string) => `/cms/pages/${slug}` as const,
  },
  verification: {
    status: "/verification/status",
    otpSend: "/verification/otp/send",
    otpVerify: "/verification/otp/verify",
    profile: "/verification/profile",
    faceSession: "/verification/face/session",
    faceComplete: "/verification/face/complete",
  },
  clips: {
    taxonomy: "/clips/taxonomy",
    librarySubmissions: "/clips/library-submissions",
    librarySubmissionsMine: "/clips/library-submissions/mine",
    accountReapply: "/clips/account/reapply",
    shareRequests: "/clips/share-requests",
    shareInbox: "/clips/share-requests/inbox",
    shareOutbox: "/clips/share-requests/outbox",
    shareRespond: (requestId: string) => `/clips/share-requests/${requestId}/respond`,
    shareCancel: (requestId: string) => `/clips/share-requests/${requestId}/cancel`,
  },
  master: {
    masterData: "/master/master-data",
  },
  trainer: {
    topTrainers: "/trainer/top-trainers",
    updateSlots: "/trainer/update-slots",
    addSlot: "/trainer/add-slot",
    updateSlot: "/trainer/update-slot",
    deleteSlot: "/trainer/delete-slot",
    getAvailability: "/trainer/get-availability",
    getSlots: "/trainer/get-slots",
    getTrainers: "/trainer/get-trainers",
    getRecentTrainees: "/trainer/get-recent-trainees",
    getTraineeClips: "/trainer/get-trainee-clips",
    myStats: "/trainer/my-stats",
    profile: "/trainer/profile",
    createMoneyRequest: "/trainer/create-money-request",
    getMoneyRequest: "/trainer/get-money-request",
    sessionExtensionRespond: "/trainer/session-extension/respond",
    instantLessonAccept: "/trainer/instant-lesson/accept",
    instantLessonDecline: "/trainer/instant-lesson/decline",
    traineeNote: (traineeId: string) => `/trainer/trainee-notes/${traineeId}` as const,
    nudgeCandidates: "/trainer/nudge-candidates",
    traineeNudge: "/trainer/trainee-nudge",
    sessionRecap: "/trainer/session-recap",
  },
  trainee: {
    getTrainersWithSlots: "/trainee/get-trainers-with-slots",
    bookSession: "/trainee/book-session",
    bookInstantMeeting: "/trainee/book-instant-meeting",
    cancelInstantLesson: "/trainee/cancel-instant-lesson",
    instantLessonEligibility: "/trainee/instant-lesson/eligibility",
    profile: "/trainee/profile",
    checkSlot: "/trainee/check-slot",
    recentTrainers: "/trainee/recent-trainers",
    favoriteTrainers: "/trainee/favorite-trainers",
    favoriteTrainer: (trainerId: string) => `/trainee/favorite-trainers/${trainerId}` as const,
    guestActivity: "/trainee/guest-activity",
    guestSeededTrainers: "/trainee/guest-activity/seeded-trainers",
    personalizedFeed: "/trainee/personalized-feed",
    sessionExtensionQuote: "/trainee/session-extension/quote",
    sessionExtensionRequest: "/trainee/session-extension/request",
    sessionExtensionCancel: "/trainee/session-extension/cancel-request",
    sessionExtensionPaymentIntent: "/trainee/session-extension/create-payment-intent",
    sessionExtensionConfirm: "/trainee/session-extension/confirm",
  },
  transaction: {
    createPaymentIntent: "/transaction/create-payment-intent",
    getPaymentIntent: "/transaction/get-payment-intent",
    createRefund: "/transaction/create-refund",
  },
  payments: {
    quote: "/payments/quote",
  },
  wallet: {
    balance: "/wallet/balance",
    ledger: "/wallet/ledger",
    earnings: "/wallet/earnings",
    trainerPulse: "/wallet/trainer-pulse",
    trainerEarningsSeries: "/wallet/trainer-earnings-series",
    trainerEarningsCsv: "/wallet/trainer-earnings.csv",
    topUpCreateIntent: "/wallet/topup/create-intent",
    topUpStatus: (topupId: string) => `/wallet/topup/${topupId}/status` as const,
    topUpConfirm: (topupId: string) => `/wallet/topup/${topupId}/confirm` as const,
    pinSet: "/wallet/pin/set",
    pinVerify: "/wallet/pin/verify",
    pinForgotRequest: "/wallet/pin/forgot/request",
    pinForgotConfirm: "/wallet/pin/forgot/confirm",
    payoutPreference: "/wallet/payout-preference",
    withdraw: "/wallet/withdraw",
    config: "/wallet/config",
    transactionDetail: (id: string) => `/wallet/transactions/${id}` as const,
    /** Saved Stripe payment methods (last-4, brand, expiry). */
    paymentMethods: "/wallet/payment-methods",
    paymentMethod: (id: string) => `/wallet/payment-methods/${id}` as const,
    paymentMethodDefault: (id: string) => `/wallet/payment-methods/${id}/default` as const,
    /** Auto top-up rule (server-stored: threshold + reload amount + source). */
    autoTopUp: "/wallet/auto-topup",
    /** Refund + payment timeline events for a transaction. */
    refundTimeline: (id: string) => `/wallet/transactions/${id}/timeline` as const,
  },
  storage: {
    clipsPresign: "/storage/clips/presign",
    clipsConfirm: "/storage/clips/confirm",
  },
  common: {
    extendSessionEndTime: "/common/extend-session-end-time",
    upload: "/common/upload",
    videoUploadUrl: "/common/video-upload-url",
    savedSessionsUploadUrl: "/common/saved-sessions-upload-url",
    getAllSavedSessions: "/common/get-all-saved-sessions",
    pdfUploadUrl: "/common/pdf-upload-url",
    getClips: "/common/get-clips",
    getSharedClips: "/common/get-shared-clips",
    getLibraryClips: "/common/get-library-clips",
    traineeClips: "/common/trainee-clips",
    deleteClip: (id: string) => `/common/delete-clip/${id}` as const,
    deleteSavedSession: (id: string) => `/common/delete-saved-session/${id}` as const,
    updateProfilePicture: "/common/update-profile-picture",
    generateThumbnail: "/common/generate-thumbnail",
    featuredContentUploadUrl: "/common/featured-content-upload-url",
  },
  report: {
    create: "/report",
    addImage: "/report/add-image",
    addSessionRecording: "/report/add-session-recording",
    removeImage: "/report/remove-image",
    cropImage: "/report/crop-image",
    get: "/report/get",
    getAll: "/report/get-all",
    deleteReport: (id: string) => `/report/delete-report/${id}` as const,
  },
  admin: {
    updateGlobalCommission: "/admin/update-global-commission",
    getGlobalCommission: "/admin/get-global-commission",
    callDiagnostics: "/admin/call-diagnostics",
    callQualitySummary: (sessionId: string) => `/admin/call-quality-summary/${sessionId}` as const,
    user360: (id: string) => `/admin/user-360/${id}` as const,
    userTimeline: (id: string) => `/admin/user-timeline/${id}` as const,
    clipPlayUrl: (clipId: string) => `/admin/clip-play-url/${clipId}` as const,
    userLessons: (id: string) => `/admin/user-lessons/${id}` as const,
    userReviews: (id: string) => `/admin/user-reviews/${id}` as const,
    userAssets: (id: string) => `/admin/user-assets/${id}` as const,
    deleteEntity: (entityType: string, entityId: string) =>
      `/admin/entity/${entityType}/${entityId}` as const,
    auditLogs: "/admin/audit-logs",
    dashboardMetrics: "/admin/dashboard-metrics",
    onlineUsers: "/admin/online-users",
  },
  notifications: {
    list: "/notifications",
    getPublicKey: "/notifications/get-public-key",
    subscription: "/notifications/subscription",
    update: "/notifications/update",
    /** Mobile-only: register/unregister device push tokens. The backend will
     *  add these endpoints; until they exist the client logs and falls back. */
    registerPushToken: "/notifications/register-push-token",
    unregisterPushToken: (deviceId: string) =>
      `/notifications/unregister-push-token/${encodeURIComponent(deviceId)}` as const,
    preferences: "/notifications/preferences",
    mute: "/notifications/mute",
    quietHours: "/notifications/quiet-hours",
  },
  promo: {
    validate: "/common/validate-promo",
    visible: "/common/visible-promos",
  },
  chat: {
    conversations: "/common/chat-conversations",
    messages: (conversationId: string) => `/common/chat-messages/${conversationId}` as const,
    send: "/common/chat-send",
    conversation: "/common/chat-conversation",
    mediaUploadUrl: "/common/chat-media-upload-url",
    mediaUploadAbort: "/common/chat-media-upload-abort",
    lessonCallSlot: (sessionId: string) =>
      `/common/lesson-call-slot/${encodeURIComponent(sessionId)}` as const,
    lessonCallSlotTakeover: (sessionId: string) =>
      `/common/lesson-call-slot/${encodeURIComponent(sessionId)}/takeover` as const,
    createGroup: "/common/chat-create-group",
    createGroupInvite: "/common/chat-create-group-invite",
    editMessage: "/common/chat-edit-message",
    deleteMessage: "/common/chat-delete-message",
    archiveConversation: "/common/chat-archive",
    unarchiveConversation: "/common/chat-unarchive",
    archivedConversations: "/common/chat-conversations?archived=true",
    deleteConversation: "/common/chat-delete-conversation",
    clearConversation: "/common/chat-clear",
    groupInvites: "/common/chat-group-invites",
    respondGroupInvite: "/common/chat-group-invite-respond",
    groupDetail: (conversationId: string) => `/common/chat-group/${conversationId}` as const,
    groupMembers: (conversationId: string) =>
      `/common/chat-group/${conversationId}/members` as const,
    groupInvite: (conversationId: string) =>
      `/common/chat-group/${conversationId}/invite` as const,
    groupRemoveMember: (conversationId: string) =>
      `/common/chat-group/${conversationId}/remove-member` as const,
    groupExit: (conversationId: string) => `/common/chat-group/${conversationId}/exit` as const,
    groupDelete: (conversationId: string) =>
      `/common/chat-group/${conversationId}/delete` as const,
    groupUpdate: (conversationId: string) =>
      `/common/chat-group/${conversationId}/update` as const,
    policy: (otherUserId: string) =>
      `/common/chat-policy?otherUserId=${encodeURIComponent(otherUserId)}` as const,
    react: "/common/chat-react",
    forward: "/common/chat-forward",
    pin: "/common/chat-pin",
    unpin: "/common/chat-unpin",
    pinned: (conversationId: string) =>
      `/common/chat-pinned/${conversationId}` as const,
    searchAll: "/common/chat-search",
    transcribe: "/common/chat-transcribe",
    disappearing: "/common/chat-disappearing",
    readReceipts: "/common/chat-read-receipts",
    scheduled: "/common/chat-scheduled",
    cancelScheduled: (id: string) => `/common/chat-scheduled/${id}` as const,
  },
  ai: {
    recommendTrainers: "/ai/recommend-trainers",
    chatAssistant: "/ai/chat-assistant",
    transcribeInput: "/ai/transcribe-input",
    lessonSummary: (sessionId: string) => `/ai/lesson-summary/${sessionId}` as const,
    tagClip: (clipId: string) => `/ai/tag-clip/${clipId}` as const,
    enhanceProfile: "/ai/enhance-profile",
    applyEnhancedProfile: "/ai/apply-enhanced-profile",
    smartSchedule: (trainerId: string) => `/ai/smart-schedule/${trainerId}` as const,
    reviewAnalysis: "/ai/review-analysis",
    smartSearch: "/ai/smart-search",
  },
} as const;
